### PR TITLE
Add battery and heart rate

### PR DESCRIPTION
**Pull request by zhenyolka**
@dmlls I've added battery and heart rate to your watchface. All works on Sim and device.

### CODE REVIEW

**Comment by dmlls** [comment]
@zhenyolka first of all, thank you for your contribution!

The Infineat watchface was designed with the goal of providing a minimalist, decluttered interface. Because of that, I decided to remove any icon that wasn't absolutely necessary. I took it as far as removing the BLE icon. However, some users said (legitimately) that this was something they needed (e.g., some of them had connectivity issues, and knowing when their watch was actually connected was important for them), so in the end I added it.

In the case of the heartrate,.. I honestly think is something non-essential, since it only provides information when the heartbeat app is on, and for that users can simply use the app, can't they?

Now, the battery icon is something different. I am someone who likes to see how much battery I have left (and I actually think the battery percentage should be more accessible in the menu). I had thought maybe **showing the icon**, but **only when the battery goes below a certain percentage**, e.g.., 40%. I think a good position would be the **bottom-left corner**, since it would be well-visible and the feeling of the watchface would still be preserved.

What do you think?

**Comment by zhenyolka** [comment]
@dmlls I think that heartrate icon isnt necessary too, but battery icon must be visible all the time. Bottom right corner would be a good place for it

**Comment by dmlls** [comment]
Hi @zhenyolka, thanks for your feedback.

There's an ongoing discussion about this on the upstream PR: https://github.com/InfiniTimeOrg/InfiniTime/pull/1024#issuecomment-1078817606.

Feel free to participate and contribute your ideas :)

**Comment by dmlls** [comment]
Closing since the battery indicator has been included in the [new release](https://github.com/dmlls/InfiniTime/releases/tag/1.9.0-1-infineat).

In any case, thanks a lot! 🙏🏻

**Pull request closed without merging**
